env:
  node: true
  es6: true
extends: 'eslint:recommended'
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 8
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
