service: ddns-updater
plugins:
  - serverless-domain-manager
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
  timeout: 3
  iamRoleStatements:
  - Effect: Allow
    Action:
      - lambda:InvokeFunction
    Resource: arn:aws:lambda:*:*:function:${self:custom.process}
  - Effect: Allow
    Action:
      - route53:ListHostedZones
      - route53:ListResourceRecordSets
      - route53:ChangeResourceRecordSets
    Resource: "*"

custom:
  domain: ${file(config.json):update_endpoint}
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  customDomain:
      basePath: ""
      domainName: ${self:custom.domain}
      stage: ${self:custom.stage}
      createRoute53Record: true

package:
 include:
    - handler.js
    - auth.js
    - ddns-updater.js

functions:
  index:
    timeout: 10
    handler: handler.index
    events:
      - http:
          path: "/"
          method: any
  update:
    timeout: 10
    handler: handler.update
    events:
      - http:
          path: update
          method: any
          authorizer: auth
  auth:
    handler: auth.auth
