service: ddns-updater
plugins:
  - serverless-domain-manager
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 128
  timeout: 3
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource: arn:aws:lambda:*:*:function:${self:custom.process}
      - Effect: Allow
        Action:
          - route53:ListHostedZones
          - route53:ListResourceRecordSets
          - route53:ChangeResourceRecordSets
        Resource: "*"

custom:
  domain: ${file(config.json):update_endpoint}
  region: ${self:provider.region}
  stage: ${sls:stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  customDomain:
      basePath: ""
      domainName: ${self:custom.domain}
      stage: ${self:custom.stage}
      createRoute53Record: true
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk
package:
  individually: true

functions:
  index:
    timeout: 10
    handler: src/handler.index
    events:
      - http:
          path: "/"
          method: any
  update:
    timeout: 10
    handler: src/handler.update
    events:
      - http:
          path: update
          method: any
          authorizer: auth
  auth:
    handler: src/auth.auth
